uploads = []
generated = []

[[outputs]]
id = "b2DQTF0RaPz7sS6h70PY1"
uri = "file://yemen-services-build.zip"
type = "unspecified"
title = "Yemen Services - Production Build"

[[outputs]]
id = "v95mGFhr6sTvYO4xedvzW"
uri = "file://yemen-services-dist.zip"
type = "unspecified"
title = "Yemen Services - dist folder (كامل)"
